import "../globals.css";

import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import Context from "../contextApi/Context";
import ProfileSIdebar from "./ProfileComponents/ProfileSIdebar";
import { getDataHandler } from "../actions/users/getData";
import { getMyProfileInfo } from "../constans/constans";
import ProfileSidebarMobile from "./ProfileComponents/ProfileSidebarMobile";
import Cookies from "js-cookie";

export const metadata = {
    title: "Profile Online-exam",
    description: "Generated by create next app",
};

export default async function ProfileLayout({ children }) {
   
    const { status, result } = await getDataHandler(getMyProfileInfo);

    return (
        <html lang="en">
            <body className="bg-gray-200 h-screen overflow-auto md:overflow-hidden text-gray-900">
                <Context>
                    <ToastContainer />

                    <div className=" block md:flex w-full flex-col md:flex-row md:h-screen h-auto">
                        {/*  desktop view sidebar menu item */}
                        <aside className=" z-[99999999] hidden md:flex w-64 h-screen overflow-y-auto  md:items-start  px-3 bg-gray-800">

                            <ProfileSIdebar profileInfo={result} />
                            <div className="h-10"></div>
                        </aside>
                        {/*  mobile view menu item */}
                        <div className=" z-[99999999] sticky top-0 block md:hidden w-full bg-red-600">
                            <ProfileSidebarMobile profileInfo={result} />
                        </div>

                        {/* Main Content */}
                        <main className="w-full z-[50] md:flex-1 p-2 md:p-10 bg-white rounded-md overflow-y-scroll">
                            {children}
                            <div className="h-10"></div>
                        </main>
                    </div>
                </Context>
            </body>
        </html>
    );
}
